export const vilages = [
  {
    name: "kardiani",
    img: "https://res.cloudinary.com/dtekdjcan/image/upload/v1678439411/tinosmiles.gr/vilages/tinos-miles-kardiani-vilage_ulcpvl.webp",
    location: "https://goo.gl/maps/zxPozpwYggJjydW88",
    description:
      "Take a walk in the vilage, and enjoy the amphitheatrical views overlooking the sea.",
    icons: ["1", "3", "5", "6"],
    order: "0",
    group: "1",
  },
  {
    name: "insternia",
    img: "https://res.cloudinary.com/dtekdjcan/image/upload/v1678285729/tinosmiles.gr/vilages/tinos-miles-isternia-vilage_t4w5a6.webp",
    description: "Cocktails, brunch  and amazing views overlooking the sea.",
    icons: ["1", "3", "5", "6", "4", "2"],
    order: "1",
    group: "1",
  },
  {
    name: "pirgos",
    img: "https://res.cloudinary.com/dtekdjcan/image/upload/v1678439803/tinosmiles.gr/vilages/tinos-miles-pirgos-vilage_mc2tlg.webp",
    description:
      "Visite the marble museum, have your coffee and local sweets in the center square.",
    icons: ["2", "3", "4", "6", "7"],
    order: "2",
    group: "1",
  },
  {
    name: "panormos",
    img: "https://res.cloudinary.com/dtekdjcan/image/upload/v1678439439/tinosmiles.gr/vilages/tinos-miles-panormos-vilage_zsk9eb.webp",
    description: "Fish taverns and a view of the sea, what else does one need.",
    icons: ["1", "4", "6"],
    order: "3",
    group: "1",
  },
  {
    name: "volax",
    img: "https://res.cloudinary.com/dtekdjcan/image/upload/v1678441225/tinosmiles.gr/vilages/tinos-miles-volax-vilage_bh7p5n.webp",
    description: "Gathering information 😃 ",
    icons: ["3", "4", "6"],
    order: "4",
    group: "2",
  },
  {
    name: "falatados",
    img: "https://res.cloudinary.com/dtekdjcan/image/upload/v1678441225/tinosmiles.gr/vilages/tinos-miles-volax-vilage_bh7p5n.webp",
    description: "Gathering information 😍",
    icons: ["3", "4", "6"],
    order: "5",
    group: "2",
  },
  {
    name: "dio xoria",
    img: "https://res.cloudinary.com/dtekdjcan/image/upload/v1678441225/tinosmiles.gr/vilages/tinos-miles-volax-vilage_bh7p5n.webp",
    description: "Gathering information 😃",
    icons: ["1", "2", "3", "4", "6"],
    order: "6",
    group: "3",
  },
  {
    name: "arnados",
    img: "https://res.cloudinary.com/dtekdjcan/image/upload/v1678441225/tinosmiles.gr/vilages/tinos-miles-volax-vilage_bh7p5n.webp",
    description: "Gathering information 😍",
    icons: ["1", "3", "4", "6"],
    order: "7",
    group: "3",
  },
  {
    name: "triantaros",
    img: "https://res.cloudinary.com/dtekdjcan/image/upload/v1678441225/tinosmiles.gr/vilages/tinos-miles-volax-vilage_bh7p5n.webp",
    description: "Gathering information 👀",
    icons: ["1", "2", "3", "4", "6"],
    order: "7",
    group: "3",
  },
  {
    name: "komi",
    img: "https://res.cloudinary.com/dtekdjcan/image/upload/v1678441225/tinosmiles.gr/vilages/tinos-miles-volax-vilage_bh7p5n.webp",
    description: "Gathering information 😍",
    icons: ["2", "6"],
    order: "8",
    group: "2",
  },
  {
    name: "agapi",
    img: "https://res.cloudinary.com/dtekdjcan/image/upload/v1678441225/tinosmiles.gr/vilages/tinos-miles-volax-vilage_bh7p5n.webp",
    description: "Gathering information 👀",
    icons: ["1", "2", "4", "6"],
    order: "9",
    group: "2",
  },
  {
    name: "krokos",
    img: "https://res.cloudinary.com/dtekdjcan/image/upload/v1678441225/tinosmiles.gr/vilages/tinos-miles-volax-vilage_bh7p5n.webp",
    description: "Gathering information 😍",
    icons: ["1", "2", "4", "6"],
    order: "9",
    group: "2",
  },
  {
    name: "loutra",
    img: "https://res.cloudinary.com/dtekdjcan/image/upload/v1678441225/tinosmiles.gr/vilages/tinos-miles-volax-vilage_bh7p5n.webp",
    description: "Gathering information 😃",
    icons: ["1", "2", "4", "6"],
    order: "9",
    group: "2",
  },
];
